config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'users/new'
  root 'static_pages#home'
  get '/about' => 'static_pages#about'
  resources :users, only:[:index, :show]
  resources :foodmenus, only:[:index,:new, :edit, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Workout", root_path, id:"logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "My Page", current_user %></li>
          <li><%= link_to "User一覧", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              ワークアウトメニュー<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "新規投稿", '#' %></li>
              <li><%= link_to "お気に入り", '#' %></li>
              <li><%= link_to "投稿一覧", '#' %></li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              フードメニュー<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "新規投稿", new_foodmenu_path %></li>
              <li><%= link_to "お気に入り", '#' %></li>
              <li><%= link_to "投稿一覧", foodmenus_path %></li>
            </ul>
          </li>

          <li><%= link_to "メッセージ", '#' %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Log in",  new_user_session_path %></li>
          <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title><%= full_title(yield(:title)) %> | Workout Motivation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <%= render "layouts/header" %>
    <div class="container">
    <%= yield %>
    <%= render "layouts/footer" %>
    </div>
  </body>
</html>